name: Health Monitor CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: List files in workspace
        run: ls -la

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code (Flake8)
        run: flake8 app.py test_app.py --count --select=E9,F63,F7,F82 --show-source

      - name: Run Unit Tests (Pytest)
        run: pytest test_app.py

  execute_and_report:
    needs: test_and_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Monitoring Script
        run: python app.py

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: health-check-report
          path: health_report.json
